### ISSUE TITLE
log4j2的靶场扫不出来，报参数不符合条件的错误

### ISSUE THREAD

**Issue by Tukali** [pmiaowu/log4j2Scan#4]
![image](https://user-images.githubusercontent.com/45891208/145934762-0027e80f-d08b-4be9-9733-32e4ac6e50bc.png)

扫描类型设置我全选了，编译也没报错，师傅帮忙看看

**Comment by pmiaowu** [comment]
我故意设置的,我该一下把,没参数就跑header头进行漏洞测试

**Comment by XTeam-Wing** [comment]
> ![image](https://user-images.githubusercontent.com/45891208/145934762-0027e80f-d08b-4be9-9733-32e4ac6e50bc.png)
> 
> 扫描类型设置我全选了，编译也没报错，师傅帮忙看看

这个靶场不是这么用的，要加参数
post /hello

payload=123

**Comment by pmiaowu** [comment]
没关系了,现在你可以下载新版本,新版本遇到你前面这种数据包会去构造请求,进行header漏洞扫描
