### ISSUE TITLE
报错ClassNotFoundException: org.yaml.snakeyaml.Yaml

### ISSUE THREAD

**Issue by t43Wiu6** [pmiaowu/log4j2Scan#7]
喵呜在吗，呼叫喵呜

![749963a4ab95ce69d1e326509258cc1](https://user-images.githubusercontent.com/40162856/146207358-bdd7a741-560b-4c94-aec1-b6736f34357e.png)

加载报了找不到Yaml类，jdk1.8和jdk12都试过了

**Comment by pmiaowu** [comment]
你好,你导入错jar了,编译完毕以后,正确的jar包在这里,./log4j2Scan/target/log4j2Scan/log4j2Scan.jar

**Comment by pmiaowu** [comment]
你试试

**Comment by pmiaowu** [comment]
这一点,在md文件里面有写哦,你在试试看

**Comment by t43Wiu6** [comment]
这我是万万没想到，谢了😅
